import React from 'react'
import Head from 'next/head'

const HeadTags = () => {
	return (
		<Head>
			<title>Movies </title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/img/icons8-cinema-32.png' />
		</Head>
	)
}

export default HeadTags
